/*
Main.java
Lindsay Simpkins
COMP 755
10/4/14

Calculates Fibonnaci numbers. 
User inputs number of Fibonacci numbers to generate by command line.
A separate thread is spawned to generate the Fibonacci numbers.
The number will be stored in an array; both threads can access it.
The parent thread outputs the sequence generated by the child thread.
The parent thread must wait for the child thread to complete.
 */

package parallelfibonacci;

public class ParallelFibonacci {

    /**
     * @param args user inputs the number of Fibonacci numbers to generate
     */
    public static void main(String[] args) {
        
    }
    
}
